# Generated by Django 5.1 on 2024-12-24 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(max_length=11)),
                ('phone_number_2', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('achieved_degree', models.CharField(max_length=100)),
                ('running_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('current_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_certificate', models.ImageField(upload_to='accounts/certificates/')),
                ('personal_photo', models.ImageField(upload_to='accounts/photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
