# Generated by Django 5.1 on 2025-01-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tutions', '0004_tuitionapplication_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tutions.tuitionapplication', verbose_name='Tuition Application'),
        ),
    ]
