# Generated by Django 5.1 on 2024-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tuition Title')),
                ('image', models.ImageField(upload_to='tuition_images/', verbose_name='Image')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class')),
                ('subjects', models.TextField(verbose_name='Subjects')),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Group')),
                ('routine', models.TextField(verbose_name='Routine')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Payment')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('google_map_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Map Link')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('details', models.TextField(verbose_name='Details')),
                ('experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Experience (Years)')),
                ('required_skills', models.TextField(blank=True, null=True, verbose_name='Required Skills')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
