# Generated by Django 5.1 on 2024-12-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutions', '0002_tuitionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpost',
            name='image',
            field=models.ImageField(upload_to='tutions/images/', verbose_name='Image'),
        ),
    ]
