# Generated by Django 5.1 on 2025-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutions', '0003_alter_tuitionpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
